---
new_page_extension: md
auto_deploy: false
admin_path: "/public"
webhook_url: 
sections:
- type: directory
  path: content/his
  label: Naveed
  create: all
  match: "**/*"
- type: directory
  path: content/hers
  label: Atiya
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  preview_docker_image: docker.io/naveedpash/zola
  mount_path: "/workspace"
  working_dir: "/workspace"
  instant_preview_command: zola build
version: 0.78.2
